- name: Создание партиции на диске "{{ disk_device }}"
  community.general.parted:
    device: "{{ disk_device }}"
    number: 1
    state: present
    part_end: 100%

- name: Создание файловой системы на партиции
  ansible.builtin.filesystem:
    fstype: xfs
    dev: "{{ disk_device }}1"

- name: Монтирование файловой системы
  ansible.builtin.mount:
    path: /data
    src: "{{ disk_device }}1"
    fstype: xfs
    state: mounted
    opts: defaults
