- name: Убедиться, что пользователь "{{ nginx_user }}" существует
  ansible.builtin.user:
    name: "{{ nginx_user }}"
    system: yes
    createhome: no

- name: Создание директории для конфигурации nginx
  ansible.builtin.file:
    path: "{{ nginx_conf_dir }}"
    state: directory
    owner: "{{ nginx_user }}"
    mode: 0700

- name: Скачивание nginx binary
  ansible.builtin.get_url:
    url: "{{ nginx_binary_url }}"
    dest: "/usr/local/bin/nginx"
    mode: '0755'

- name: Копирование темплейтов конфигурации nginx
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nginx_conf_dir }}"
    owner: "{{ nginx_user }}"
    mode: 0600
  loop: "{{ query('fileglob', 'templates/nginx/*') }}"

- name: Создание systemd unit файла для nginx
  ansible.builtin.template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
  notify: restart nginx

- name: Запуск и включение в автозагрузку nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started
